# Generated by Django 5.0.3 on 2024-03-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_authors_commentpost_name_commentpost_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='author_image',
        ),
    ]
