# Generated by Django 5.0.3 on 2024-03-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_image',
            new_name='post_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
