# Generated by Django 5.0.3 on 2024-03-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_myuser_bio_remove_myuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
