# Generated by Django 5.0.3 on 2024-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_commentpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='img_3.jpg', null=True, upload_to='users/'),
        ),
    ]
