# Generated by Django 5.0.3 on 2024-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/person_2.jpg', null=True, upload_to='users/'),
        ),
    ]
