# Generated by Django 5.0.3 on 2024-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
